### PR TITLE
Add flag which enables fade-in and fade-out of the items during animation

### PR DESCRIPTION
**Pull request by pmkowal**
This Pull Request enables fade-in and fade-out of the items during animation. It uses `fadeItems` flag to enable this feature. By default the flag is set to `NO`.

### CODE REVIEW

**Comment by pmkowal** [comment]
Hi @alattis is it possible to merge this feature into your main repo?

**Comment by pmkowal** [comment]
Thanks @alattis!

**Comment by pmkowal** [comment]
@alattis Is it possible to bump the version from v1.0 and add the tag?

**Comment by alattis** [comment]
done, it was actually 0.1.0, now its 1.0.0

**Comment by pmkowal** [comment]
:+1:

**Comment by pmkowal** [comment]
@alattis on cocoapods site it's still 0.1.0: https://cocoapods.org/pods/ALRadial

**Pull request merged**
